// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: class.sql

package db

import (
	"context"
	"database/sql"
)

const createClass = `-- name: CreateClass :one
INSERT INTO "Class"(
    name, head_teacher
)VALUES (
            $1,$2
        ) RETURNING id, name, head_teacher, created_by, updated_by, created_at, updated_at
`

type CreateClassParams struct {
	Name        string        `json:"name"`
	HeadTeacher sql.NullInt64 `json:"headTeacher"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Name, arg.HeadTeacher)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HeadTeacher,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassById = `-- name: GetClassById :one
SELECT id, name, head_teacher, created_by, updated_by, created_at, updated_at FROM "Class"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClassById(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClassById, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HeadTeacher,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllClasses = `-- name: ListAllClasses :many
SELECT id, name, head_teacher, created_by, updated_by, created_at, updated_at FROM "Class"
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListAllClassesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllClasses(ctx context.Context, arg ListAllClassesParams) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listAllClasses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HeadTeacher,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassHeadTeacher = `-- name: UpdateClassHeadTeacher :one
UPDATE  "Class"
SET  head_teacher = $2, updated_at = now()
where id = $1
RETURNING id, name, head_teacher, created_by, updated_by, created_at, updated_at
`

type UpdateClassHeadTeacherParams struct {
	ID          int64         `json:"id"`
	HeadTeacher sql.NullInt64 `json:"headTeacher"`
}

func (q *Queries) UpdateClassHeadTeacher(ctx context.Context, arg UpdateClassHeadTeacherParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, updateClassHeadTeacher, arg.ID, arg.HeadTeacher)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HeadTeacher,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
