// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: lesson.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO "Lesson"(
    name,course_id,start_hour,end_hour, week_day, classroom
)VALUES (
            $1,$2,$3,$4,$5,$6
        ) RETURNING id, name, course_id, teacher_id, start_hour, end_hour, week_day, classroom, created_by, updated_by, created_at, updated_at
`

type CreateLessonParams struct {
	Name      string         `json:"name"`
	CourseID  sql.NullInt64  `json:"courseID"`
	StartHour sql.NullTime   `json:"startHour"`
	EndHour   sql.NullTime   `json:"endHour"`
	WeekDay   sql.NullString `json:"weekDay"`
	Classroom sql.NullString `json:"classroom"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, createLesson,
		arg.Name,
		arg.CourseID,
		arg.StartHour,
		arg.EndHour,
		arg.WeekDay,
		arg.Classroom,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.TeacherID,
		&i.StartHour,
		&i.EndHour,
		&i.WeekDay,
		&i.Classroom,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassSchedule = `-- name: GetClassSchedule :one
SELECT "Lesson".id, "Lesson".name, course_id, "Lesson".teacher_id, start_hour, end_hour, week_day, classroom, "Lesson".created_by, "Lesson".updated_by, "Lesson".created_at, "Lesson".updated_at, "Course".id, "Course".name, "Course".teacher_id, semester_id, class_id, dates, "Course".created_by, "Course".updated_by, "Course".created_at, "Course".updated_at
FROM "Lesson"
INNER JOIN "Course"
ON  "Lesson".course_id = "Course".id AND "Course".class_id = $1
`

type GetClassScheduleRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	CourseID    sql.NullInt64  `json:"courseID"`
	TeacherID   sql.NullInt64  `json:"teacherID"`
	StartHour   sql.NullTime   `json:"startHour"`
	EndHour     sql.NullTime   `json:"endHour"`
	WeekDay     sql.NullString `json:"weekDay"`
	Classroom   sql.NullString `json:"classroom"`
	CreatedBy   sql.NullInt64  `json:"createdBy"`
	UpdatedBy   sql.NullInt64  `json:"updatedBy"`
	CreatedAt   sql.NullTime   `json:"createdAt"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
	ID_2        int64          `json:"id2"`
	Name_2      string         `json:"name2"`
	TeacherID_2 sql.NullInt64  `json:"teacherID2"`
	SemesterID  sql.NullInt32  `json:"semesterID"`
	ClassID     sql.NullInt32  `json:"classID"`
	Dates       []time.Time    `json:"dates"`
	CreatedBy_2 sql.NullInt64  `json:"createdBy2"`
	UpdatedBy_2 sql.NullInt64  `json:"updatedBy2"`
	CreatedAt_2 sql.NullTime   `json:"createdAt2"`
	UpdatedAt_2 sql.NullTime   `json:"updatedAt2"`
}

func (q *Queries) GetClassSchedule(ctx context.Context, classID sql.NullInt32) (GetClassScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, getClassSchedule, classID)
	var i GetClassScheduleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.TeacherID,
		&i.StartHour,
		&i.EndHour,
		&i.WeekDay,
		&i.Classroom,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.Name_2,
		&i.TeacherID_2,
		&i.SemesterID,
		&i.ClassID,
		pq.Array(&i.Dates),
		&i.CreatedBy_2,
		&i.UpdatedBy_2,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getLessonsOfCourse = `-- name: GetLessonsOfCourse :one
SELECT id, name, course_id, teacher_id, start_hour, end_hour, week_day, classroom, created_by, updated_by, created_at, updated_at FROM "Lesson"
WHERE course_id = $1
`

func (q *Queries) GetLessonsOfCourse(ctx context.Context, courseID sql.NullInt64) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonsOfCourse, courseID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.TeacherID,
		&i.StartHour,
		&i.EndHour,
		&i.WeekDay,
		&i.Classroom,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherSchedule = `-- name: GetTeacherSchedule :one
SELECT "Lesson".id, "Lesson".name, course_id, "Lesson".teacher_id, start_hour, end_hour, week_day, classroom, "Lesson".created_by, "Lesson".updated_by, "Lesson".created_at, "Lesson".updated_at, "Course".id, "Course".name, "Course".teacher_id, semester_id, class_id, dates, "Course".created_by, "Course".updated_by, "Course".created_at, "Course".updated_at
FROM "Lesson"
INNER JOIN "Course"
ON  "Lesson".course_id = "Course".id AND "Course".teacher_id = $1
`

type GetTeacherScheduleRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	CourseID    sql.NullInt64  `json:"courseID"`
	TeacherID   sql.NullInt64  `json:"teacherID"`
	StartHour   sql.NullTime   `json:"startHour"`
	EndHour     sql.NullTime   `json:"endHour"`
	WeekDay     sql.NullString `json:"weekDay"`
	Classroom   sql.NullString `json:"classroom"`
	CreatedBy   sql.NullInt64  `json:"createdBy"`
	UpdatedBy   sql.NullInt64  `json:"updatedBy"`
	CreatedAt   sql.NullTime   `json:"createdAt"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
	ID_2        int64          `json:"id2"`
	Name_2      string         `json:"name2"`
	TeacherID_2 sql.NullInt64  `json:"teacherID2"`
	SemesterID  sql.NullInt32  `json:"semesterID"`
	ClassID     sql.NullInt32  `json:"classID"`
	Dates       []time.Time    `json:"dates"`
	CreatedBy_2 sql.NullInt64  `json:"createdBy2"`
	UpdatedBy_2 sql.NullInt64  `json:"updatedBy2"`
	CreatedAt_2 sql.NullTime   `json:"createdAt2"`
	UpdatedAt_2 sql.NullTime   `json:"updatedAt2"`
}

func (q *Queries) GetTeacherSchedule(ctx context.Context, teacherID sql.NullInt64) (GetTeacherScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, getTeacherSchedule, teacherID)
	var i GetTeacherScheduleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.TeacherID,
		&i.StartHour,
		&i.EndHour,
		&i.WeekDay,
		&i.Classroom,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.Name_2,
		&i.TeacherID_2,
		&i.SemesterID,
		&i.ClassID,
		pq.Array(&i.Dates),
		&i.CreatedBy_2,
		&i.UpdatedBy_2,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const updateLessonTimeAndPlace = `-- name: UpdateLessonTimeAndPlace :one
UPDATE  "Lesson"
SET  start_hour= $2,end_hour=$3, week_day=$4,classroom=$5,updated_at = now()
where id = $1
RETURNING id, name, course_id, teacher_id, start_hour, end_hour, week_day, classroom, created_by, updated_by, created_at, updated_at
`

type UpdateLessonTimeAndPlaceParams struct {
	ID        int64          `json:"id"`
	StartHour sql.NullTime   `json:"startHour"`
	EndHour   sql.NullTime   `json:"endHour"`
	WeekDay   sql.NullString `json:"weekDay"`
	Classroom sql.NullString `json:"classroom"`
}

func (q *Queries) UpdateLessonTimeAndPlace(ctx context.Context, arg UpdateLessonTimeAndPlaceParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLessonTimeAndPlace,
		arg.ID,
		arg.StartHour,
		arg.EndHour,
		arg.WeekDay,
		arg.Classroom,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CourseID,
		&i.TeacherID,
		&i.StartHour,
		&i.EndHour,
		&i.WeekDay,
		&i.Classroom,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
