// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateSchool(ctx context.Context, name string) (School, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSchool(ctx context.Context, id int64) error
	GetSchoolbyId(ctx context.Context, id int64) (School, error)
	GetSchoolbyName(ctx context.Context, name string) (School, error)
	GetUserbyId(ctx context.Context, id int64) (User, error)
	ListSchools(ctx context.Context, arg ListSchoolsParams) ([]School, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error)
}

var _ Querier = (*Queries)(nil)
