// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddUserToClass(ctx context.Context, arg AddUserToClassParams) (UserRoleClass, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreateMark(ctx context.Context, arg CreateMarkParams) (Mark, error)
	CreateRoleForUser(ctx context.Context, arg CreateRoleForUserParams) (UserRole, error)
	CreateRoles(ctx context.Context, arg CreateRolesParams) ([]Role, error)
	CreateSchool(ctx context.Context, name string) (School, error)
	CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMark(ctx context.Context, id int64) error
	DeleteSchool(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetClassById(ctx context.Context, id int64) (Class, error)
	GetClassSchedule(ctx context.Context, classID int64) ([]GetClassScheduleRow, error)
	GetClassWithStudents(ctx context.Context, id int64) ([]GetClassWithStudentsRow, error)
	GetCourseByID(ctx context.Context, id int64) (Course, error)
	GetCourseMarks(ctx context.Context, id int64) ([]GetCourseMarksRow, error)
	GetCoursesOfSchool(ctx context.Context, schoolID int64) ([]GetCoursesOfSchoolRow, error)
	GetCurrentSemester(ctx context.Context) (Semester, error)
	GetLessonsOfCourse(ctx context.Context, courseID int64) ([]Lesson, error)
	GetMarkByID(ctx context.Context, id int64) (Mark, error)
	GetRolebyId(ctx context.Context, id int64) (Role, error)
	GetRoles(ctx context.Context) ([]Role, error)
	GetSchoolbyId(ctx context.Context, id int64) (School, error)
	GetSchoolbyName(ctx context.Context, name string) (School, error)
	GetSemesterbyId(ctx context.Context, id int64) (Semester, error)
	GetSemesters(ctx context.Context) ([]Semester, error)
	GetStudentCourseMarks(ctx context.Context, arg GetStudentCourseMarksParams) ([]GetStudentCourseMarksRow, error)
	GetTeacherSchedule(ctx context.Context, teacherID int64) ([]GetTeacherScheduleRow, error)
	GetUserClassByUserRoleId(ctx context.Context, userRoleID int64) (UserRoleClass, error)
	GetUserRoleById(ctx context.Context, id int64) (UserRole, error)
	GetUserRoleByUserId(ctx context.Context, userID int64) ([]UserRole, error)
	GetUserbyEmail(ctx context.Context, email string) (User, error)
	GetUserbyId(ctx context.Context, id int64) (User, error)
	ListAllClasses(ctx context.Context) ([]Class, error)
	ListCoursesOfClass(ctx context.Context, classID int64) ([]Course, error)
	ListCoursesOfTeacher(ctx context.Context, teacherID int64) ([]Course, error)
	ListSchools(ctx context.Context, arg ListSchoolsParams) ([]School, error)
	UpdateClassHeadTeacher(ctx context.Context, arg UpdateClassHeadTeacherParams) (Class, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateCourseAbsencebyId(ctx context.Context, id int64) (Mark, error)
	UpdateCourseDates(ctx context.Context, arg UpdateCourseDatesParams) (Course, error)
	UpdateCourseMarksbyId(ctx context.Context, arg UpdateCourseMarksbyIdParams) (Mark, error)
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserHeadTeacherRole(ctx context.Context, arg UpdateUserHeadTeacherRoleParams) (UserRole, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserRoleClass(ctx context.Context, arg UpdateUserRoleClassParams) (UserRoleClass, error)
}

var _ Querier = (*Queries)(nil)
