apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "2"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: "api.scoala-mea.link"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: school-service
              port:
                number: 80
  tls:
  - hosts:
      - api.scoala-mea.link
    secretName: school-api-cert